FROM python:3.12-slim

WORKDIR /app

# Устанавливаем системные зависимости
RUN apt-get update && apt-get install -y --no-install-recommends \
 postgresql-client \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Установка uv
RUN pip install --no-cache-dir uv

# Копируем зависимости
COPY pyproject.toml uv.lock ./

# Устанавливаем ВСЕ зависимости (включая dev)
RUN pip install --no-cache-dir -e ".[dev]"

# Копируем entrypoint отдельно
COPY entrypoint.sh /entrypoint.sh

# Делаем entrypoint исполняемым
RUN chmod +x /entrypoint.sh

# Копируем код
COPY . .

# Точка входа
ENTRYPOINT ["/entrypoint.sh"]

# Команда по умолчанию
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]