# Generated by Django 6.0 on 2025-12-16 07:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('account_number', models.CharField(max_length=20, verbose_name='Номер счета')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('bik', models.CharField(max_length=9, verbose_name='БИК')),
                ('corr_account', models.CharField(max_length=20, verbose_name='Корреспондентский счет')),
            ],
            options={
                'verbose_name': 'Реквизиты получателя',
                'verbose_name_plural': 'Реквизиты получателей',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['inn'], name='payouts_rec_inn_917772_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма выплаты')),
                ('currency', models.CharField(choices=[('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов'), ('JPY', 'Японская иена'), ('CNY', 'Китайский юань'), ('CHF', 'Швейцарский франк'), ('CAD', 'Канадский доллар'), ('AUD', 'Австралийский доллар'), ('NZD', 'Новозеландский доллар'), ('RUB', 'Российский рубль')], max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('completed', 'Выполнена'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('recipient_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payouts.recipientdetails', verbose_name='Реквизиты получателя')),
            ],
            options={
                'verbose_name': 'Заявка на выплату',
                'verbose_name_plural': 'Заявки на выплату',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payouts_pay_status_a5ad2e_idx'), models.Index(fields=['created_at'], name='payouts_pay_created_b65d12_idx'), models.Index(fields=['currency'], name='payouts_pay_currenc_42f9c2_idx')],
            },
        ),
    ]
